### ISSUE TITLE
Compile Error for iPhone 5.0 Simulator: framework not found CoreSurface

### ISSUE THREAD

**Issue by LeftoverNoodles** [rileytestut/SNES4iOS#1]
I havent tithed my $99 yet, but trying to test it in the simulator kicked up this....  Any advice?

Ld /Users/Geg/Library/Developer/Xcode/DerivedData/SNES4iOS-grlkytckpzpehqaiywehwbwsuxed/Build/Products/Debug-iphonesimulator/SNES4iOS.app/SNES4iOS normal i386
    cd /Users/Geg/Documents/Xcode/SNES4iOS
    setenv MACOSX_DEPLOYMENT_TARGET 10.6
    setenv PATH "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang -arch i386 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -L/Users/Geg/Library/Developer/Xcode/DerivedData/SNES4iOS-grlkytckpzpehqaiywehwbwsuxed/Build/Products/Debug-iphonesimulator -L/Users/Geg/Documents/Xcode/SNES4iOS/src/snes4iphone_src -F/Users/Geg/Library/Developer/Xcode/DerivedData/SNES4iOS-grlkytckpzpehqaiywehwbwsuxed/Build/Products/Debug-iphonesimulator -F/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/PrivateFrameworks -F/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.2.sdk/System/Library/PrivateFrameworks -F/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk/System/Library/PrivateFrameworks -filelist /Users/Geg/Library/Developer/Xcode/DerivedData/SNES4iOS-grlkytckpzpehqaiywehwbwsuxed/Build/Intermediates/SNES4iOS.build/Debug-iphonesimulator/SNES4iOS.build/Objects-normal/i386/SNES4iOS.LinkFileList -mmacosx-version-min=10.6 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -Xlinker -no_implicit_dylibs -D__IPHONE_OS_VERSION_MIN_REQUIRED=50000 -framework AVFoundation -framework MediaPlayer -framework Foundation -framework UIKit -framework CoreGraphics -framework GameKit -framework QuartzCore -framework CoreSurface -framework IOSurface -lpocketsnes -framework AudioToolbox -lz -lIOKit -o /Users/Geg/Library/Developer/Xcode/DerivedData/SNES4iOS-grlkytckpzpehqaiywehwbwsuxed/Build/Products/Debug-iphonesimulator/SNES4iOS.app/SNES4iOS

ld: warning: directory not found for option '-F/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.3.sdk/System/Library/PrivateFrameworks'
ld: warning: directory not found for option '-F/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS3.2.sdk/System/Library/PrivateFrameworks'
ld: framework not found CoreSurface
Command /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang failed with exit code 1

**Comment by rileytestut** [comment]
SNES4iOS wasn't designed to be run on the iOS Simulator. It uses Private APIs to increase performance, but these APIs aren't available on the simulator

**Comment by LeftoverNoodles** [comment]
Suspected as much.  Thanks for confirming.

**Comment by mxswd** [comment]
Oh I see. LOL

**Comment by mariotatis** [comment]
I'm getting the same error 4 years later :) CoreSurface running it directly to an iPhone 6 device.
Any suggestions?
