### ISSUE TITLE
Hardcoded /Developer paths don't work in Xcode 4.3

### ISSUE THREAD

**Issue by mistydemeo** [rileytestut/SNES4iOS#2]
In Xcode 4.3, the developer paths moved from /Developer to /Applications/Xcode.app/Contents/Developer. Maybe the location of include paths and clang should be based on the output of `xcode-select -print-path` rather than hardcoded?

**Comment by rileytestut** [comment]
Thank you, I've pushed the changes to Github. Check out the newest version :)
