### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by MarkWestside** [rileytestut/SNES4iOS#20]
I use Xcode 4.5 DP4 and get over 200 warnings and the following Apple Mach-O Linker Error:
Reference to symbol (which has not been assigned an address) _refreshScreenSurface in _gp_setFramebuffer from ~/iSkythe-SNES4iOS-b01bfa6/src/snes4iphone_src/libpocketsnes.a(iphone_sdk.o) for architecture armv7

I get the same error on Xcode 4.4.1.

Any ideas?

**Comment by Vybesoft** [comment]
Same problem here.

**Comment by rileytestut** [comment]
I'm looking into this, unfortunately I don't know what the exact problem is right now. My only suggestion would be to install Xcode 4.4 in the meantime and compile.

**Comment by rockstarjoe** [comment]
I, too, have run in to this.  Would be happy to test if you have any suggestions. Thanks!

**Comment by jlturner** [comment]
I'm having this problem also. I'm running Xcode 4.4 on Mountain Lion.

```
...from hundreds of warnings prior:
ld: warning: ARM function not 4-byte aligned: ApuFF from /Users/jlturner/Downloads/jlturner-SNES4iOS-b01bfa6/src/snes4iphone_src/libpocketsnes.a(spc700a.o)
ld: warning: ARM function not 4-byte aligned: _Spc700JumpTab from /Users/jlturner/Downloads/jlturner-SNES4iOS-b01bfa6/src/snes4iphone_src/libpocketsnes.a(spc700a.o)
ld: warning: PIE disabled. Absolute addressing (perhaps -mdynamic-no-pic) not allowed in code signed PIE, but used in gbspecial from /Users/jlturner/Downloads/jlturner-SNES4iOS-b01bfa6/src/snes4iphone_src/libpocketsnes.a(os9x_65c816.o). To fix this warning, don't compile with -mdynamic-no-pic or link with -Wl,-no_pie
ld: reference to symbol (which has not been assigned an address) _refreshScreenSurface in _gp_setFramebuffer from /Users/jlturner/Downloads/jlturner-SNES4iOS-b01bfa6/src/snes4iphone_src/libpocketsnes.a(iphone_sdk.o) for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Showing first 200 warnings only
```

**Comment by jkirsons** [comment]
If you change "Build Settings / Linking / Perform Single-Object Prelink" to Yes, it resolves the error.
Not the warnings though...

**Comment by jlturner** [comment]
Yep, setting the Perform Single-Object Prelink allowed me build successfully. Thanks jkirsons!

**Comment by rockstarjoe** [comment]
This worked for me too.  Thanks!
