### ISSUE TITLE
Will you add iCade? (not an actual issue)

### ISSUE THREAD

**Issue by laxking97** [rileytestut/SNES4iOS#8]
I am not (yet) a developer (but I'm making an app and I will be soon), and in a few weeks, I'm getting an iCade and I was just wondering if you will add iCade support for this, and the GBA4iPhone? That would be great, but if not, its still the SNES for the iPhone! Also, I'm wondering if you are making any other emulators for developers? Thanks!

**Comment by rileytestut** [comment]
Yes I will most certainly be adding iCade support to both SNES4iOS and GBA4iOS, probably around the time the iCade Mobile is released. As for other emulators, my next project is N64, but that may take a while :)

**Comment by FuerstBismark** [comment]
Sorry for rescurrecting this ancient issue :x
Is the ION iCade mobile supported in GBA4iOS v.2.0.1 ?

**Comment by lonkelle** [comment]
iCade in GBA4iOS would be perfect for nes30 controller support - but I don't think he ever actually got around to adding support for it in any of his emulators (though, I do hear it's easy to add)..
