### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by darvin** [rileytestut/SNES4iOS#9]
error: failed to launch '/Users/darvin/Library/Developer/Xcode/DerivedData/SNES4iOS-bfzfkxuqotqikfenedxedndhbled/Build/Products/Debug-iphoneos/SNES4iOS.app/SNES4iOS' -- No such file or directory (/Users/darvin/Library/Developer/Xcode/DerivedData/SNES4iOS-bfzfkxuqotqikfenedxedndhbled/Build/Products/Debug-iphoneos/SNES4iOS.app/SNES4iOS)

clean build

**Comment by darvin** [comment]
Oh, i was building not project but workspace

**Comment by rileytestut** [comment]
Try deleting the Derived Data from Organizer, then Clean your target, then try building again.

**Comment by rileytestut** [comment]
Ah well then glad you got it fixed :)
